airtai/fastagency-studio

examples/nats/README.md, examples/nats/faststream_backend.py, pyproject.toml
=> Port example to FastStream and use faststream v0.5.0

fastagency/app.py, fastagency/models/llms.py, tests/models/test_llms.py, tests/test_app.py
=> Refactoring

.devcontainer/python-3.10/devcontainer.json, .devcontainer/python-3.11/devcontainer.json, .devcontainer/python-3.12/devcontainer.json, .devcontainer/python-3.9/devcontainer.json, .github/workflows/docker_cleanup.yml, .github/workflows/enforcer.yaml, .github/workflows/test.yaml, Dockerfile, docker-compose.yaml, scripts/deploy.sh, scripts/run_server.sh
=> Setup pipelines

pyproject.toml
=> Pin fastapi version

.devcontainer/python-3.10/devcontainer.json, .devcontainer/python-3.11/devcontainer.json, .devcontainer/python-3.12/devcontainer.json, .devcontainer/python-3.9/devcontainer.json, .github/workflows/docker_cleanup.yml, .github/workflows/enforcer.yaml, .github/workflows/test.yaml, Dockerfile, docker-compose.yaml, pyproject.toml, scripts/deploy.sh, scripts/run_server.sh
=> Add PRs #61, #65

.github/workflows/test.yaml
=> Pull git lfs files in github actions

.github/workflows/test.yaml, pyproject.toml
=> Add pre commit check to ci

fastagency/app.py, fastagency/models/registry.py, tests/app/test_openai_extensively.py, tests/models/test_registry.py
=> Removing wrappers from routes

.github/workflows/test.yaml
=> Deploy frontend to serve via nginx

fastagency/app.py, fastagency/models/llms/openai.py, tests/app/test_openai_extensively.py, tests/models/agents/test_assistant.py, tests/models/llms/test_openai.py
=> OpenAI key validator replaced by field pattern

.github/workflows/test.yaml, docs/docs/SUMMARY.md, docs/docs/en/api/fastagency/models/agents/web_surfer/BingAPIKey.md, fastagency/app.py, fastagency/models/__init__.py, fastagency/models/agents/__init__.py, fastagency/models/agents/_base.py, fastagency/models/agents/web_surfer.py, fastagency/models/llms/openai.py, fastagency/models/registry.py, tests/app/test_get_schemas.py, tests/app/test_openai_extensively.py, tests/models/agents/test_assistant.py, tests/models/agents/test_web_surfer.py, tests/models/llms/test_openai.py, tests/models/test_registry.py
Add PRs #95, #96, #97, #98, #99
=> Add PRs #95, #96, #97, #98, #99

app/main.wasp
=> Add Google Analytics

fastagency/models/agents/web_surfer.py, tests/models/agents/test_web_surfer.py
=> Fix wrong type of Bing API key in WebSurfer

fastagency/models/teams/multi_agent_team.py
=> Multiple agent simplified

Dockerfile
=> Install node in fastapi docker

.github/workflows/test.yaml, scripts/deploy.sh
=> Pass DATABASE_URL to fastapi docker

.github/workflows/test.yaml, pyproject.toml
=> Packages updated

.github/workflows/test.yaml
=> Use docker login action version 3.1.0

.devcontainer/devcontainer.env, .devcontainer/python-3.10/docker-compose.yml, .devcontainer/python-3.11/devcontainer.json, .devcontainer/python-3.11/docker-compose.yml, .devcontainer/python-3.12/devcontainer.json, .devcontainer/python-3.12/docker-compose.yml, .devcontainer/python-3.9/devcontainer.json, .devcontainer/python-3.9/docker-compose.yml, .devcontainer/setup.sh, .secrets.baseline
=> Fix bugs in devcontainer setup and environment variables

docker-compose.yaml
=> Pass DATABASE_URL to fastapi app

app/src/client/components/ModelItem.tsx, app/src/client/components/buildPage/UserPropertyHandler.tsx, app/src/client/interfaces/BuildPageInterfaces.ts, app/src/client/tests/DynamicFormBuilder.test.tsx, app/src/client/tests/buildPageUtils.test.ts, app/src/client/utils/buildPageUtils.ts, fastagency/models/base.py, tests/app/test_model_routes.py, tests/app/test_openai_extensively.py, tests/models/agents/test_assistant.py, tests/models/agents/test_web_surfer.py, tests/models/llms/test_azure.py, tests/models/llms/test_openai.py, tests/models/test_registry.py
=> 126 add names to every object

tests/models/agents/test_assistant.py
=> Add missing name

nats-docker-compose.yaml, nats_server.conf, scripts/deploy_nats.sh, scripts/run_server.sh
=> Fix bugs in deploying NATS docker and update NATS config

tests/models/agents/test_assistant.py, tests/models/agents/test_web_surfer.py, tests/models/teams/test_multi_agents_team.py, tests/models/teams/test_two_agents_team.py
=> Add validation tests

docs/docs/SUMMARY.md, docs/docs/en/api/fastagency/faststream_app/ping_handler.md, fastagency/faststream_app.py
=> Use DOMAIN env var to construct deployed nats url

app/src/client/components/DynamicFormBuilder.tsx, app/src/client/interfaces/BuildPageInterfaces.ts, app/src/client/tests/DynamicFormBuilder.test.tsx, app/src/client/tests/buildPageUtils.test.ts, app/src/client/utils/buildPageUtils.ts
=> Show correct reference value while editing existing property

fastagency/faststream_app.py, fastagency/io/app.py, scripts/run_server.sh
=> Start IONats faststream server in docker

app/src/client/app/BuildPage.tsx, app/src/client/app/CheckoutPage.tsx, app/src/client/app/PlayGroundPage.tsx, app/src/client/app/PricingPage.tsx, app/src/client/auth/Auth.tsx, app/src/client/auth/authWrapper.tsx, app/src/client/components/ChatSidebar.tsx, app/src/client/components/TosAndMarketingEmails.tsx, app/src/client/components/TosAndMarketingEmailsModal.tsx, app/src/client/components/UserActionButton.tsx, app/src/client/components/buildPage/ToolBoxes.tsx
=> UI polishing

app/src/client/app/layout/ChatLayout.tsx, app/src/client/tests/commonUtils.test.ts, app/src/client/utils/commonUtils.ts, app/src/server/websocket/nats.ts, app/src/server/websocket/webSocket.js
=> 172 chatclientinput updates all previous agent conversation history

app/src/client/app/PlayGroundPage.tsx, app/src/server/websocket/nats.ts, fastagency/io/app.py, fastagency/io/ionats.py, tests/test_nats.py
=> Use less subjects to keep messages from server sequential

.github/workflows/deploy-nats.yaml
=> Remove unnecessary check in deploy nats (#198)

fastagency/io/ionats.py, tests/test_nats.py
=> Background task

fastagency/io/ionats.py, tests/test_nats.py
* Use anyio task group
* Use asyncio background tasks
=> Background task (#203)

.github/workflows/test.yaml, app/src/client/components/AnimatedCharacterLoader.tsx, app/src/client/components/ConversationList.tsx, app/src/client/components/SmartSuggestionButton.tsx, app/src/client/components/SmartSuggestionCheckbox.tsx, app/src/client/components/buildPage/UserPropertyHandler.tsx, app/src/client/interfaces/BuildPageInterfaces.ts, app/src/client/tests/buildPageUtils.test.ts, app/src/client/utils/buildPageUtils.ts, app/src/client/utils/chatUtils.ts, fastagency/models/agents/web_surfer.py, tests/models/agents/test_web_surfer.py
=> Dev #205, #206, #212, #213

scripts/deploy_nats.sh
=> Fix typo in deploy nats script

.github/workflows/deploy-nats.yaml, scripts/deploy_nats.sh
=> Add variable to delete jetstream subjects

app/src/client/components/DynamicFormBuilder.tsx, app/src/client/components/ModelItem.tsx, app/src/client/interfaces/BuildPageInterfaces.ts, app/src/client/services/commonService.ts, app/src/client/tests/DynamicFormBuilder.test.tsx, app/src/client/tests/buildPageUtils.test.ts, app/src/client/utils/buildPageUtils.ts, app/src/server/actions.ts, app/src/server/websocket/nats.ts, docs/docs/SUMMARY.md, docs/docs/en/api/fastagency/app/mask.md, docs/docs/en/api/fastagency/app/validate_secret_model.md, docs/docs/en/api/fastagency/io/ionats/ServerResponseModel.md, docs/docs/en/api/fastagency/io/ionats/TerminateModel.md, fastagency/app.py, fastagency/io/ionats.py, pyproject.toml, tests/app/test_model_routes.py, tests/app/test_openai_extensively.py, tests/test_nats.py
Merge #214, #234, #236 and #239
=> Dev #214, #234, #236 and #239 

fastagency/io/ionats.py
=> Close dynamic subscriber after chat exits

docs/docs/SUMMARY.md, docs/docs/en/api/fastagency/models/teams/base/register_toolbox_functions.md, docs/docs/en/api/fastagency/models/teams/multi_agent_team/AutogenMultiAgentTeam.md, docs/docs/en/api/fastagency/models/teams/two_agent_teams/AutogenTwoAgentTeam.md, docs/docs/en/api/fastagency/models/toolboxes/toolbox/FunctionInfo.md, fastagency/io/ionats.py, fastagency/models/agents/assistant.py, fastagency/models/agents/base.py, fastagency/models/agents/user_proxy.py, fastagency/models/agents/web_surfer.py, fastagency/models/applications/application.py, fastagency/models/base.py, fastagency/models/llms/azure.py, fastagency/models/llms/openai.py, fastagency/models/teams/base.py, fastagency/models/teams/multi_agent_team.py, fastagency/models/teams/two_agent_teams.py, fastagency/models/toolboxes/toolbox.py, tests/models/agents/test_assistant.py, tests/models/agents/test_user_proxy.py, tests/models/agents/test_web_surfer.py, tests/models/llms/test_azure.py, tests/models/llms/test_openai.py, tests/models/teams/test_base.py, tests/models/teams/test_multi_agents_team.py, tests/models/teams/test_two_agents_team.py, tests/models/toolboxes/test_toolbox.py, tests/test_nats.py
=> Implement toolbox refactoring

fastagency/openapi/client.py, tests/conftest.py, tests/models/toolboxes/test_toolbox.py
=> Fix problem in function calling in toolbox

docker-compose.yaml, fastagency/weather_app.py, scripts/run_server.sh
=> Update non ssl port to 9001 and prepare for https

fastagency/constants.py, fastagency/models/llms/azure.py, tests/models/llms/test_azure.py
=> Remove latest as api version option

Dockerfile
=> Include wasp installation path in PATH

pyproject.toml
=> Upgrade packages

fastagency/saas_app_generator.py, tests/test_saas_app_generator.py
=> Use the email and name from the gh token for initial commit

app/src/client/components/AppNavBar.tsx, app/src/client/landing-page/LandingPage.tsx
=> Update version label from beta to alpha

app/src/client/landing-page/contentSections.ts
=> Add GitHub link to footer

app/src/client/components/DynamicFormBuilder.tsx, docs/docs/SUMMARY.md, docs/docs/en/api/fastagency/saas_app_generator/InvalidFlyTokenError.md, docs/docs/en/api/fastagency/saas_app_generator/InvalidGHTokenError.md, fastagency/app.py, fastagency/saas_app_generator.py, tests/app/test_model_routes.py, tests/test_saas_app_generator.py
=> App deployment is failing in staging

docker-compose.yaml
=> Remove unnecessary loki logging driver

fastagency/models/applications/application.py, tests/app/test_model_routes.py, tests/models/applications/test_application.py
=> Limit the length of the application name to comply with dns rules

app/main.wasp, app/src/client/app/DocsPage.tsx, app/src/client/landing-page/contentSections.ts
=> Add documentation tab in the navigation

app/main.wasp, app/migrations/20240619070132_add_new_column_in_user_model_to_store_the_user_setup_status/migration.sql, app/src/client/App.tsx, app/src/client/app/DocsPage.tsx, app/src/client/components/DynamicFormBuilder.tsx, app/src/client/landing-page/contentSections.ts, app/src/server/actions.ts, app/src/server/auth/setUsername.ts, app/src/server/scripts/usersSeed.ts, fastagency/models/applications/application.py, tests/app/test_model_routes.py, tests/models/applications/test_application.py
=> Dev #386 #384 #383 #385

fastagency/io/ionats.py
=> Handle callback error

scripts/run_server.sh
=> Remove useless cmd and use 4 workers in prod

app/src/client/components/DynamicFormBuilder.tsx, app/src/client/components/SelectTeamToChat.tsx, fastagency/io/ionats.py, fastagency/models/applications/application.py, scripts/run_server.sh
=> Dev #393, #395, #396

app/src/client/app/DocsPage.tsx
=> Update docs video URL

app/src/client/app/DocsPage.tsx, app/src/client/components/DynamicFormBuilder.tsx
=> Dev #399 #400

app/src/client/landing-page/LandingPage.tsx
=> Add tutorial video to home page (#402)

app/src/server/websocket/nats.ts
=> Handle infinite loading in Chat

app/src/client/app/BuildPage.tsx, app/src/client/components/CustomSidebar.tsx, app/src/client/components/DynamicFormBuilder.tsx, app/src/client/components/ModelItem.tsx, app/src/client/components/buildPage/Deployments.tsx, app/src/client/components/buildPage/UserPropertyHandler.tsx, app/src/client/tests/buildPageUtils.test.ts, app/src/client/utils/constants.ts, docs/docs/SUMMARY.md, docs/docs/en/api/fastagency/app/deployment_chat.md, docs/docs/en/api/fastagency/models/deployments/deployment/Deployment.md, fastagency/app.py, fastagency/helpers.py, fastagency/models/__init__.py, fastagency/models/applications/__init__.py, fastagency/models/deployments/__init__.py, fastagency/models/deployments/deployment.py, fastagency/models/secrets/fly_token.py, fastagency/saas_app_generator.py, tests/app/test_get_schemas.py, tests/app/test_model_routes.py, tests/models/deployments/test_deployment.py, tests/test_saas_app_generator.py
=> Rename application to deployment

app/src/client/app/BuildPage.tsx, app/src/client/components/CustomSidebar.tsx, app/src/client/components/DynamicFormBuilder.tsx, app/src/client/components/ModelItem.tsx, app/src/client/components/buildPage/Deployments.tsx, app/src/client/components/buildPage/UserPropertyHandler.tsx, app/src/client/tests/buildPageUtils.test.ts, app/src/client/utils/constants.ts, app/src/server/websocket/nats.ts, docs/docs/SUMMARY.md, docs/docs/en/api/fastagency/app/deployment_chat.md, docs/docs/en/api/fastagency/models/deployments/deployment/Deployment.md, fastagency/app.py, fastagency/helpers.py, fastagency/models/__init__.py, fastagency/models/applications/__init__.py, fastagency/models/deployments/__init__.py, fastagency/models/deployments/deployment.py, fastagency/models/secrets/fly_token.py, fastagency/saas_app_generator.py, tests/app/test_get_schemas.py, tests/app/test_model_routes.py, tests/models/deployments/test_deployment.py, tests/test_saas_app_generator.py
=> Dev #409 #416

migrations/20240625114706_rename_applications_to_deployments/migration.sql
=> Show existing applications in the deployments tab (#422)

.github/workflows/test.yaml
=> Add necessary environment to deploy frontend and deploy node

.github/workflows/test.yaml
=> Update needs field to fix deploy errors

.github/workflows/test.yaml
=> Update about to be deprecated environment command

docs/docs/SUMMARY.md, docs/docs/en/api/fastagency/app/deployment_ping.md, fastagency/app.py, tests/app/test_model_routes.py
=> Add ping route

fastagency/saas_app_generator.py, tests/test_saas_app_generator.py
=> Fix staging deployment

docker-compose.yaml, nats-docker-compose.yaml
=> Always restart docker

scripts/deploy_node.sh
=> Always restart node docker

docker-compose.yaml, nats-docker-compose.yaml, scripts/deploy_node.sh
=> Dev #455, #456

fastagency/models/agents/web_surfer.py, fastagency/models/llms/together.py
=> Fix retrieving bing api key in websurfer

app/package-lock.json, app/package.json, app/src/client/components/ChatForm.tsx, app/src/client/components/SelectTeamToChat.tsx, app/src/client/tests/ChatForm.test.tsx
=> Support for multiline chat message

fastagency/models/llms/together.py, pyproject.toml
=> Bug fix and updated packages

.github/workflows/publish_coverage.yml
=> Read coverage files from pipeline.yaml

.github/workflows/pipeline.yaml, .github/workflows/test.yaml, .secrets.baseline, scripts/test.sh
=> Refactor CI: remove public environment

fastagency/helpers.py, fastagency/models/agents/assistant.py, fastagency/models/agents/user_proxy.py, fastagency/models/agents/web_surfer.py, fastagency/models/base.py, fastagency/models/deployments/deployment.py, fastagency/models/llms/anthropic.py, fastagency/models/llms/azure.py, fastagency/models/llms/openai.py, fastagency/models/llms/together.py, fastagency/models/secrets/fly_token.py, fastagency/models/secrets/github_token.py, fastagency/models/teams/base.py, fastagency/models/teams/multi_agent_team.py, fastagency/models/teams/two_agent_teams.py, fastagency/models/toolboxes/toolbox.py, fastagency/saas_app_generator.py, migrations/20240702085925_add_fly_io_name_and_repo_name_to_json_str_column/migration.sql, tests/app/test_model_routes.py, tests/app/test_openai_extensively.py, tests/conftest.py, tests/models/agents/test_assistant.py, tests/models/agents/test_web_surfer.py, tests/models/deployments/test_deployment.py, tests/models/llms/test_anthropic.py, tests/models/llms/test_llm_keys.py, tests/models/llms/test_openai.py, tests/models/teams/test_two_agents_team.py, tests/models/toolboxes/test_toolbox.py, tests/test_saas_app_generator.py
=> Dev #487, #486

fastagency/saas_app_generator.py, tests/test_saas_app_generator.py
=> Set the GH token as an action secret in the deployment repository

app/main.wasp, app/src/client/app/BuildPage.tsx
=> Add dynamic routing for BuildPage

.github/workflows/pipeline.yaml
=> Fix deployment in CI

.gitattributes, README.md, docs/docs/assets/img/FA-Secondary-LOGO.jpg
=> branding added to README (#541)

app/src/client/components/ConversationList.tsx, app/src/client/components/SelectTeamToChat.tsx
=> Chat messages not preserving users original formatting new line characters

.github/workflows/deploy.yaml
=> Add missing ssh key

.github/workflows/deploy.yaml, scripts/deploy-auth-callout.sh
=> Add docker login to deploy auth callout service

app/src/client/components/SelectTeamToChat.tsx
=> Prevent duplicate chat creation while selecting a team

.github/workflows/deploy.yaml, .github/workflows/docker-cleanup.yml, docker-compose/fastapi/docker-compose.yaml, scripts/deploy-auth-callout.sh, scripts/deploy-node.sh, scripts/deploy.sh
=> Use explicit docker image names instead of reading from env var

app/src/client/app/TutorialPage.tsx, app/src/client/components/ChatForm.tsx, app/src/client/components/SelectTeamToChat.tsx, app/src/client/tests/ChatForm.test.tsx
=> Make playground chat responsive

.github/workflows/deploy.yaml, .github/workflows/docker-cleanup.yml, app/src/client/app/TutorialPage.tsx, app/src/client/components/ChatForm.tsx, app/src/client/components/SelectTeamToChat.tsx, app/src/client/tests/ChatForm.test.tsx, docker-compose/fastapi/docker-compose.yaml, scripts/deploy-auth-callout.sh, scripts/deploy-node.sh, scripts/deploy.sh
=> Dev #568, #571

.devcontainer/setup.sh, .github/workflows/deploy.yaml, .github/workflows/pipeline.yaml, .github/workflows/test.yaml, Dockerfile
=> Hardcode wasp version in workflow files

.devcontainer/setup.sh, .github/workflows/deploy.yaml, .github/workflows/pipeline.yaml, .github/workflows/test.yaml, Dockerfile
=> Fix wasp version (#576)

fastagency/models/llms/together.py, tests/models/llms/test_together.py
=> Update default model for TogetherAI

.devcontainer/setup.sh, .github/workflows/deploy.yaml, .github/workflows/pipeline.yaml, .github/workflows/test.yaml, Dockerfile, app/main.wasp, app/schema.prisma, app/src/client/admin/components/Header.tsx, app/tsconfig.json
=> Migrate wasp from 013x to 014x

app/main.wasp, app/src/client/components/form/SelectInput.tsx, app/src/client/landing-page/LandingPage.tsx, app/src/client/landing-page/contentSections.ts
=> Rename tutorial to tutorials in navigation

Dockerfile
=> Change fastagency directory to fastagency_studio

app/src/client/components/ChatForm.tsx, app/src/client/tests/ChatForm.test.tsx
=> Enable typing in chat box while processing but disable submit button and form submission

app/main.wasp, app/package-lock.json, app/package.json, app/src/client/Main.css, app/src/client/app/BuildPage.tsx, app/src/client/app/layout/ChatLayout.tsx, app/src/client/components/CustomSidebar.tsx, app/src/client/components/SelectTeamToChat.tsx, app/src/client/components/form/DynamicForm.tsx, app/src/client/components/form/SelectInput.tsx, app/src/client/tests/SelectInput.test.tsx, app/src/client/tests/buildPageUtils.test.ts, app/src/client/tests/usePropertyReferenceValues.test.ts, app/src/client/utils/buildPageUtils.ts, app/src/client/utils/constants.ts
=> Replace none dropdown option with a clear button

app/main.wasp, app/package-lock.json, app/package.json, app/src/client/Main.css, app/src/client/app/BuildPage.tsx, app/src/client/app/layout/ChatLayout.tsx, app/src/client/components/ChatForm.tsx, app/src/client/components/CustomSidebar.tsx, app/src/client/components/SelectTeamToChat.tsx, app/src/client/components/form/DynamicForm.tsx, app/src/client/components/form/SelectInput.tsx, app/src/client/tests/ChatForm.test.tsx, app/src/client/tests/SelectInput.test.tsx, app/src/client/tests/buildPageUtils.test.ts, app/src/client/tests/usePropertyReferenceValues.test.ts, app/src/client/utils/buildPageUtils.ts, app/src/client/utils/constants.ts
=> Dev #614, #615, #616

app/src/client/components/buildPage/DynamicForm.tsx, app/src/client/components/buildPage/PropertySchemaParser.ts, app/src/client/components/buildPage/UserProperty.tsx, app/src/client/components/buildPage/usePropertyManager.ts, app/src/client/components/buildPage/usePropertySchemaParser.ts, app/src/client/tests/PropertySchemaParser.test.ts, app/src/client/tests/mocks.ts
=> UI bug while updating the max consecutive auto reply field is not showing the existing value

.github/dependabot.yml, .github/workflows/pipeline.yaml, pyproject.toml
=> Cleanup dependencies

app/src/client/components/CustomBreadcrumb.tsx, app/src/client/components/SelectTeamToChat.tsx, app/src/client/components/buildPage/DynamicForm.tsx, app/src/client/components/buildPage/PropertySchemaParser.ts, app/src/client/components/buildPage/UserProperty.tsx, app/src/client/components/buildPage/useFormHandler.ts, app/src/client/components/buildPage/usePropertyManager.ts, app/src/client/tests/UserProperty-e2e.test.tsx
=> Show breadcrumbs to indicate the form depth

pyproject.toml
=> Update fastagency library repo url

.devcontainer/python-3.10/devcontainer.json, .devcontainer/python-3.10/docker-compose.yml, .devcontainer/python-3.11/devcontainer.json, .devcontainer/python-3.11/docker-compose.yml, .devcontainer/python-3.12/devcontainer.json, .devcontainer/python-3.12/docker-compose.yml, .devcontainer/python-3.9/devcontainer.json, .devcontainer/python-3.9/docker-compose.yml
=> Update devcontainer files

.devcontainer/python-3.10/devcontainer.json, .devcontainer/python-3.10/docker-compose.yml, .devcontainer/python-3.11/devcontainer.json, .devcontainer/python-3.11/docker-compose.yml, .devcontainer/python-3.12/devcontainer.json, .devcontainer/python-3.12/docker-compose.yml, .devcontainer/python-3.9/devcontainer.json, .devcontainer/python-3.9/docker-compose.yml, app/src/client/components/CustomBreadcrumb.tsx, app/src/client/components/SelectTeamToChat.tsx, app/src/client/components/buildPage/DynamicForm.tsx, app/src/client/components/buildPage/PropertySchemaParser.ts, app/src/client/components/buildPage/UserProperty.tsx, app/src/client/components/buildPage/useFormHandler.ts, app/src/client/components/buildPage/usePropertyManager.ts, app/src/client/tests/UserProperty-e2e.test.tsx, pyproject.toml
=> Merge PRs #658, #659, #660

.github/workflows/pipeline.yaml, pyproject.toml, scripts/run-server.sh
=> Integrate studio submodule refactoring

app/src/client/components/buildPage/PropertySchemaParser.ts, app/src/client/interfaces/BuildPageInterfaces.ts, app/src/client/tests/DynamicForm.test.tsx, app/src/client/tests/PropertySchemaParser.test.ts, app/src/client/tests/UserProperty-e2e.test.tsx, app/src/client/tests/mocks.ts
=> Use property title as field label

app/src/client/components/buildPage/usePropertyManager.ts, app/src/server/actions.ts
=> Unable to update an existing secret name

app/src/shared/constants.ts
=> Update GitHub url in web app

Dockerfile
=> Ignore installed blinker and install only necessary submodules

.github/workflows/update-release-notes.yaml, app/src/client/components/buildPage/useFormHandler.ts, app/src/client/tests/UserProperty-e2e.test.tsx, app/src/server/actions.ts, auth_callout/package.json, auth_callout/pnpm-lock.yaml, migrations/20240910115224_make_json_str_name_unique_per_user/migration.sql
Merge PR's: #717, #718, #719, #721
=> Dev #717, #718, #719, #721

app/src/client/App.tsx, app/src/client/components/buildPage/DynamicForm.tsx, app/src/client/components/buildPage/FormField.tsx, app/src/client/components/buildPage/PropertySchemaParser.ts, app/src/client/components/buildPage/usePropertyManager.ts, app/src/client/components/form/TextArea.tsx, app/src/client/components/form/TextInput.tsx, app/src/client/interfaces/BuildPageInterfaces.ts, app/src/client/tests/PropertySchemaParser.test.ts, app/src/client/tests/UserProperty-e2e.test.tsx, app/src/client/tests/mocks.ts, app/src/client/utils/constants.ts, app/tailwind.config.cjs
=> Mark specific form fields as non-editable while editing the property

fastagency_studio/models/llms/together.py, tests/conftest.py
=> Fix together test

tests/conftest.py, tests/models/agents/test_web_surfer.py, tests/models/llms/test_openai.py
=> Fix code vulnerability
